---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: shashi-sample-app
  name: sample-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

